name: CI

on:
  push:
    branches: [ main ]
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.2
        with:
          check-latest: true
      
      - name: Run a one-line script
        run: npm install
        
      - name: Deploy
        run: npm run deploy
